### ISSUE TITLE
Figlets

### ISSUE THREAD

**Issue by LB6YD** [kencormack/pistar-lastqso#1]
Hi. Thank you for this nice addition to Pi-Star.
Is it possible to have the fonts 1,2 and 3 filled with colour?
I find the text rather difficult to read when it is just outlined.
I think that part is named "toilet" in the SSH-helper program by WA1GOV Arthur.
No shading PSE.
BTW, decimal numbers in the QRG info should be 4 digits, and not rounded to 3  :-)
TIA for considering this.
LB6YD Gaute
lb6ydham((at))gmail.com

**Comment by kencormack** [comment]
Good evening!

I am currently working on v2.01, and have just increased the QRG precision to 4 decimal places, in that version.  I'm going to see what else users find, that might need to be addressed, before I push that update.
As for the figlet fonts, there is no way to manipulate a specific font beyond the ways described in "man figlet".  Basically, you get to play with how scrunched together the letters are (the kerning), but not much else.  In that regard, I let figlet's default kerning apply.  If I simply tried to use "reverse colors" for the fonts, everything would look worse than it does now (I tried it).  Unfortunately, there are very few figlet fonts out there on the Internet that look "attractive", but that are still small enough to adequately fit on a (worst case) 80x24 SSH session display.

Myself, I've grown accustomed to the "small" font (#1), and prefer it when I'm sitting at my desk.  When I'm moving around the room (cleaning, doing laundry, or whatever), I use the ansi_shadow font (#4), which my eyes can see from across the room.


Ken

    On Sunday, September 5, 2021, 05:10:35 PM EDT, LB6YD ***@***.***> wrote:  
 
 


Hi. Thank you for this nice addition to Pi-Star.
Is it possible to have the fonts 1,2 and 3 filled with colour?
I find the text rather difficult to read when it is just outlined.
I think that part is named "toilet" in the SSH-helper program by WA1GOV Arthur.
No shading PSE.
BTW, decimal numbers in the QRG info should be 4 digits, and not rounded to 3 :-)
TIA for considering this.
LB6YD Gaute
lb6ydham((at))gmail.com
