### ISSUE TITLE
Disable console colors 

### ISSUE THREAD

**Issue by shaposhnikoff** [kencormack/pistar-lastqso#2]
Hello!
How can I turn off the coloring output, i mean disable all colors in console ?
Thanks, Maksym, UT3UDX

**Comment by kencormack** [comment]
Maksym - That was a very simple change (and an excellent idea.) I've just implemented a new commandline option... -m | --mono.
All the colors are defined in variables. Passing that new option simply sets all the color variables to null.  I've just tested, and it looks great. 🙂

It will appear in version 2.01, which I will push to github later today. I'll need to update the usage, help screen, the README, etc., first.

Thank you again, for the excellent suggestion!

**Comment by kencormack** [comment]
This has been added to v2.01.  :)
Ken

    On Monday, September 6, 2021, 06:44:06 AM EDT, Shaposhnikoff ***@***.***> wrote:  
 
 


Hello!
How can I turn off the coloring output, i mean disable all colors in console ?
Thanks, Maksym, UT3UDX
