### ISSUE TITLE
Option to disable logo does not seem to work

### ISSUE THREAD

**Issue by khaytsus** [kencormack/pistar-lastqso#3]
Script doesn't seem to handle -l or --logo and also don't see it in the code offhand except in the help section.  The logo is cute and all, but ;)

**Comment by kencormack** [comment]
This option is planned, but I jumped the gun, added to the help, but then hadn't implemented it yet.  It will be added to the next release.  In the meantime, I have stripped mention of it from the help, and updated the screenshots.  Look for it in a later release.

**Comment by kencormack** [comment]
Version 2.04 now supports this feature.
