### ISSUE TITLE
V2.12 Port

### ISSUE THREAD

**Issue by LB6YD** [kencormack/pistar-lastqso#5]
Hi Ken, just installed V2.12.
I do not have a display on my JumboSpot, but I had PORT: set to dev/ttyAMA0.
That was also reported in the T field.
I changed Port to NONE and applied changes, restarted the V2.12, but still get PORT: ttyAMA0
Just FYI
Very much enjoying the program.
LB6YD Gaute

**Comment by kencormack** [comment]
The port you are seeing is the communication channel to the modem, not the display.  Changing whether or not you have a display does not change the device node through which the radio communication occurs.  If you run "sudo pistar-findmodem" you will see that this is the port where the modem exists, regardless of the presence, or type, of display.
