### ISSUE TITLE
BER Not Displayed Properly

### ISSUE THREAD

**Issue by techfixpros** [kencormack/pistar-lastqso#6]
The BER is not being displayed properly for NET source, but is shown correctly for RF source to the HAT:

Brandmeister
![image](https://user-images.githubusercontent.com/7028086/162587466-a548dd01-750d-4e77-8574-02121a1ba69b.png)

TGIF
![image](https://user-images.githubusercontent.com/7028086/162588382-11ea5fbd-d112-4979-9153-7c98593cd836.png)

RPi 3B v1.2
MMDVM_HS_Dual_Hat v1.6.0
lastqso v2.17
Pi-Star v4.1.6 - W0CHP dashboard & binaries
Configured as Duplex Repeater

Please let me know what add'l information needed from me.

**Comment by kencormack** [comment]
Greetings -

This is interesting.  I would like to suggest you first pull updates to the "user.csv" file, by launching pistar-lastqso with the "-c" (or --csv) option, on the commandline.  Perhaps something is corrupt in your present copy of the file that is skewing things.

Other things to try would include rebooting, and pulling down a fresh copy of the script.  Please let me know which of the above you perform, and what changes, if any, occur.

**Comment by kencormack** [comment]
You mentioned in your other issue ("Tx/Rx Frequencies are not Displayed"), that you were running some custom binaries.  I suspect that just as that package does not write the TX and RX frequencies to the log, it likely does not entirely replicate the format of other log entries normally written to the MMDVM* logfile.

**Comment by techfixpros** [comment]
I am running it with -c right now and the user.csv showed downloaded. It did not resolve the issue.
Would you be willing to look at the MMDVM log and see if it is standard, or possibly adaptable to maybe use a - switch to use that mode?

**Comment by kencormack** [comment]
My suggestion to run the "-c" option was based on an assumption that you were running the standard pi-star distribution, not a third-party package.

Unfortunately, I can not dedicate any effort to reworking all the parsing, based on a third party package that I do not run.  The amount of work it takes to both get the program to generate all the types of logfile records needed (to be sure I get them all), and then to conditionally branch my script's logic to decide when to employ to different parsings, is just not something I would be interested in undertaking.

**Comment by techfixpros** [comment]
@kencormack , could you provide a log file snippet that lastqso uses to parse out the data using stock binaries, please? If so, I will fork and modify to my needs.

**Comment by kencormack** [comment]
Even in the pi-star logs, the position of the BER can vary.  If you would like to examine how the script currently parses the BER value, look at the following, within the script:

What follows applies to version 2.17 of pistar-lastqso.

In function fnMAIN_LOOP(), the individual log entries are define as $RECORD.  After picking out the date, time, and mode (whether DMR, YSF, or whatever), the remainder of the log line is stored in $LOGREC_REMAINING_DATA.

Line 2567 in fnMAIN_LOOP() calls the function fnDMR_GET_NET_BER().  Line 2578 in fnMAIN_LOOP() calls the function fnDMR_GET_RF_BER().  Those two functions (fnDMR_GET_NET_BER and fnDMR_GET_RF_BER) are where the BER is parsed.

If you adjust those two functions to match whatever your log is giving you, you should be on your way (assuming no other differences exist in the log data elsewhere in those log lines.)

I can offer no other assistance with this, as the script is written for pi-star.  As your setup is not Andrew's official pi-star distribution, you will need to reverse-engineer your logs to determine what further parsing is needed.

Ken
