### ISSUE TITLE
Tx/Rx Frequencies are not Displayed

### ISSUE THREAD

**Issue by techfixpros** [kencormack/pistar-lastqso#7]
The Tx and Rx frequencies are not displayed properly (all zeros).

![image](https://user-images.githubusercontent.com/7028086/162589568-f40f0a42-fab0-4597-b427-f19cf82be44c.png)

Current Tx: 434.450 Rx: 439.450

RPi 3B v1.2
MMDVM_HS_Dual_Hat v1.6.0
lastqso v2.17
Pi-Star v4.1.6 - W0CHP dashboard & binaries
Configured as Duplex Repeater

**Comment by kencormack** [comment]
Interesting.

The TX and RX frequencies are pulled directly from the /var/log/pi-star/MMDVM* logfile.  That logfile contains data put there by the MMDVMHost process.  Please run the following command, and let me know what it returns...

grep "[RT]X Frequency" /var/log/pi-star/MMDVM-2022-04-10.log    (or whatever your active log is, by the time you see this.)

Thanks.

**Comment by techfixpros** [comment]
Nothing is returned. Unless this is possible in some cases, I wouldn't worry about it as it may be an issue with the custom W0CHP binaries.

![image](https://user-images.githubusercontent.com/7028086/162596631-b54bd8d7-9e88-4ec1-8f43-82f4a4625eff.png)

**Comment by kencormack** [comment]
Ah.  I see.  Whatever custom binaries are in use on that system are not replicating precisely, the identical logfile formats of the "standard" pi-star MMDVMHost daemon.  Pistar-lastqso was written specifically for the official pistar distribution only, and relies on the very specific placement of fields within each logfile entry, when parsed by the script.

**Comment by techfixpros** [comment]
Just for other users, the issue with frequencies not showing up was MMDVM log level was set to 2. Changing to 1 and restarting lastqso now shows correct frequencies instead of 0's.

pi-star@pi-star(ro):pi-star$ grep "[RT]X Frequency" /var/log/pi-star/MMDVM-2022-04-11.log
D: 2022-04-11 00:46:51.479     TX Frequency: 434450000Hz (434450000Hz)
D: 2022-04-11 00:46:53.787     RX Frequency: 439450000Hz
D: 2022-04-11 00:46:53.787     TX Frequency: 434450000Hz

![image](https://user-images.githubusercontent.com/7028086/162648160-fae8724b-44f6-4dbd-bd03-1fac81313db7.png)
