### ISSUE TITLE
lastqso v3.00 DStar

### ISSUE THREAD

**Issue by LB6YD** [kencormack/pistar-lastqso#9]
Hi Ken,
please see attached zip-file with putty img. and PiStar log.
My call is the TX (RF) signal.
Will this be of any help regarding display of RF DStar signal in lastqso v3.00?
TNX for the nice addition to PiStar.
Best 73`s
LB6YD Gaute

[lastqso_v3.00.zip](https://github.com/kencormack/pistar-lastqso/files/9724077/lastqso_v3.00.zip)

**Comment by kencormack** [comment]
Perfect!  I'll have some time later today, to play around with the sample log entries you attached.
Ken

    On Thursday, October 6, 2022 at 06:47:41 AM EDT, LB6YD ***@***.***> wrote:  
 
 


Hi Ken,
please see attached zip-file with putty img. and PiStar log.
My call is the TX (RF) signal.
Will this be of any help regarding display of RF DStar signal in lastqso v3.00?
TNX for the nice addition to PiStar.
Best 73`s
LB6YD Gaute

lastqso_v3.00.zip

**Comment by kencormack** [comment]
Greetings, Gaute -

I think you will find version 3.01 to your liking.  Thanks to your sample log, support for D-Star RF log entries has been added.
I have [acknowledged](https://github.com/kencormack/pistar-lastqso#special-thanks) your contribution at the bottom of the README page.

**Comment by kencormack** [comment]
Closed
